version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:${USERNAME}/workspaces/frontend
      - /usr/src/app/node_modules:cached
    restart: always
    environment:
      NODE_ENV: production
    networks:
      - react-express


  backend:
    restart: always
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:${USERNAME}/workspaces/backend
      - ${USERNAME}/workspaces/backend/node_modules:cached
    depends_on:
      - postgres
    networks:
      - express-postgres
      - react-express
    expose:
      - 3000


  postgres:
    image: postgres:12.1-alpine
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - hexagendb_data:/data/postgres/
    networks:
      - express-postgres
    expose:
      - 5432

networks:
  express-postgres:
  react-express:

volumes:
  hexagendb_data:
