name: ci

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    strategy:
      matrix:
        node: [lts/*]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Setup @antfu's agnostic package manager
        run: pnpm install -g @antfu/ni

      - name: Clean install
        run: nci

      - name: Lint
        run: nr lint

      - name: Check types
        run: nr check-types

  test:
    runs-on: ${{ matrix.os}}

    strategy:
      matrix:
        node: [lts/*]
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Setup @antfu's agnostic package manager
        run: pnpm install -g @antfu/ni

      - name: Clean install
        run: nci

      - name: Build
        run: nr build --if-present

      - name: Unit tests
        run: nr test --if-present

      # - name: Upload build artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: build
      #     path: dist


